# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_exam_app', '0002_auto_20180223_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='travel_end_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='travel_start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
