# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_exam_app', '0003_auto_20180223_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
