# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_exam_app', '0004_trip_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='plan',
        ),
    ]
